In [1]:
import numpy as np
import string


# Generates a random invertible matrix of a given size.


In [19]:
def generate_key_matrix(size=2):
   
    while True:
        matrix = np.random.randint(1, 26, size=(size, size))
        if np.linalg.det(matrix) != 0:  # Check if the matrix is invertible
            return matrix





# Converts text to a numerical matrix. Each character is represented by its ASCII value.

In [20]:
def text_to_matrix(text, size=2):
 
    # Pad text to fit the matrix size
    while len(text) % size != 0:
        text += ' '  # Padding with spaces

    text_values = [ord(char) - ord('a') + 1 for char in text.lower()]  # Convert to numbers
    return np.array(text_values).reshape(-1, size)


# Converts a numerical matrix back to text.

In [21]:
def matrix_to_text(matrix):

   
    
    text = ''
    for value in matrix.flatten():
        text += chr(int(value) + ord('a') - 1)
    return text


In [22]:
# Generate a 2x2 key matrix
key_matrix = generate_key_matrix(size=2)
inverse_key_matrix = np.linalg.inv(key_matrix)

key_matrix, inverse_key_matrix  # Display the matrices


(array([[23, 10],
        [21,  3]]),
 array([[-0.0212766 ,  0.07092199],
        [ 0.14893617, -0.16312057]]))

# DECRYPTION

In [24]:
def encrypt_text(text, key_matrix):
    """
    Encrypts the text using the key matrix.
    """
    text_matrix = text_to_matrix(text, size=key_matrix.shape[0])
    encrypted_matrix = np.dot(text_matrix, key_matrix)  # Matrix multiplication
    return encrypted_matrix

def decrypt_text(encrypted_matrix, inverse_key_matrix):
    """
    Decrypts the text using the inverse of the key matrix.
    """
    decrypted_matrix = np.dot(encrypted_matrix, inverse_key_matrix)
    # Rounding and converting back to integers for text conversion
    decrypted_matrix = np.round(decrypted_matrix).astype(int)
    return matrix_to_text(decrypted_matrix)

# Example text
example_text = "hello world"

# Encrypt the text
encrypted_matrix = encrypt_text(example_text, key_matrix)

# Decrypt the text
decrypted_text = decrypt_text(encrypted_matrix, inverse_key_matrix)

encrypted_matrix, decrypted_text  # Display the encrypted matrix and decrypted text



(array([[  289,    95],
        [  528,   156],
        [ -999,   -42],
        [  844,   275],
        [  666,   216],
        [-1252,  -152]]),
 'hello world ')